name=nPM1300
version=1.0.0
author=Suraj Yadav
maintainer=Suraj Yadav
sentence=Arduino library for the Nordic nPM1300 PMIC.
paragraph=Arduino compatible library providing I2C drivers for the Nordic nPM1300 PMIC including power rails, battery charging, monitoring, GPIO and LED control.
category=Device Control
url=https://github.com/Suraj2930/npm1300-arduino
architectures=*
depends=Wire